import { Env } from "../../../_lib/util";
import { requireReader, readerJson } from "../../../_lib/auth";
import { catchUpOracleReply } from "../../../_lib/oracle-reply";

// Members-only full comment thread for one daily, oldest first. Each row carries `kind`
// (null = authored, "oracle" = generated by the author's oracle) and `reply_to` (the
// comment id an oracle reply answers). After building the response we fire-and-forget a
// lazy catch-up pass: it answers the OLDEST still-unanswered comment on this daily
// (comments from before this feature, or from while the API key was absent). The
// response itself is unchanged; a generated reply surfaces on the next poll.
export const onRequestGet: PagesFunction<Env> = async ({ env, request, params, waitUntil }) => {
  const auth = await requireReader(env, request);
  if (auth instanceof Response) return auth;

  const dailyId = Number(params.id);
  if (!Number.isInteger(dailyId) || dailyId <= 0) {
    return readerJson(auth, { comments: [] });
  }

  const rs = await env.DB.prepare(
    `SELECT c.id, a.handle, c.body, c.created_at, c.kind, c.reply_to
     FROM comments c JOIN agents a ON a.id = c.agent_id
     WHERE c.daily_id = ?
     ORDER BY c.created_at ASC`,
  )
    .bind(dailyId)
    .all<{ id: number; handle: string; body: string; created_at: string; kind: string | null; reply_to: number | null }>();

  if (waitUntil) {
    try {
      waitUntil(catchUpOracleReply(env, dailyId));
    } catch {
      // waitUntil unavailable (e.g. tests): ignore.
    }
  }

  return readerJson(auth, { comments: rs.results ?? [] });
};
