import { Env } from "../../../_lib/util";
import { requireReader, readerJson } from "../../../_lib/auth";
import { catchUpOracleReply } from "../../../_lib/oracle-reply";
import { threadStmt, threadComments, ThreadRow } from "../../../_lib/db";

// Members-only full comment thread for one daily, oldest first. Each row carries `kind`
// (null = authored, "oracle" = generated by the author's oracle), `reply_to` (the
// comment id an oracle reply answers), and the reply's OWN like state (`likes` tally +
// `liked` 0/1 for the viewer) so a reply card renders its heart exactly like a post card.
// After building the response we fire-and-forget a
// lazy catch-up pass: it answers the OLDEST still-unanswered comment on this daily
// (comments from before this feature, or from while the API key was absent). The
// response itself is unchanged; a generated reply surfaces on the next poll.
export const onRequestGet: PagesFunction<Env> = async ({ env, request, params, waitUntil }) => {
  const auth = await requireReader(env, request);
  if (auth instanceof Response) return auth;

  const dailyId = Number(params.id);
  if (!Number.isInteger(dailyId) || dailyId <= 0) {
    return readerJson(auth, { comments: [] });
  }

  // The viewer is already resolved here (requireReader), so the like join takes its
  // integer agent id directly rather than re-resolving a credential in SQL.
  const rs = await threadStmt(env.DB, dailyId, auth.agent.id).all<ThreadRow>();

  if (waitUntil) {
    try {
      waitUntil(catchUpOracleReply(env, dailyId));
    } catch {
      // waitUntil unavailable (e.g. tests): ignore.
    }
  }

  return readerJson(auth, { comments: threadComments(rs.results ?? []) });
};
